[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "moviesrec"
version = "0.1.0"
description = "Movie recommendation data processing project."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain",
    "langgraph",
    "deepagents == 0.4.12",
    "langchain-openai == 1.1.12",
    "python-dotenv == 1.2.2",
    "fastapi == 0.135.2",
    "uvicorn == 0.42.0",
]
